# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dsp_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mw_dsp(object):
    def setupUi(self, mw_dsp):
        mw_dsp.setObjectName("mw_dsp")
        mw_dsp.resize(800, 600)
        mw_dsp.setMinimumSize(QtCore.QSize(800, 600))
        mw_dsp.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(mw_dsp)
        self.centralwidget.setObjectName("centralwidget")
        mw_dsp.setCentralWidget(self.centralwidget)

        self.retranslateUi(mw_dsp)
        QtCore.QMetaObject.connectSlotsByName(mw_dsp)

    def retranslateUi(self, mw_dsp):
        _translate = QtCore.QCoreApplication.translate
        mw_dsp.setWindowTitle(_translate("mw_dsp", "MainWindow"))
